### ISSUE TITLE
Nested ObservableArray not calling the correct ArrayBindingObserver initialiser in .observe()

### ISSUE THREAD

**Issue by toriaezunama** [yankodimitrov/SignalKit#14]
When I take the following sample code from the Readme.md `performBatchUpdate` doesn't work. 

```
let sectionOne = ObservableArray([1, 2])
let sectionTwo = ObservableArray([3, 4])
let list = ObservableArray<ObservableArray<Int>>([sectionOne, sectionTwo])

list.observe()
   .bindTo(tableView: tableView, dataSource: dataSource)
   .addTo(signalsBag)

list.performBatchUpdate { collection in
   collection[0].append(22)
   collection[0].removeAtIndex(0)
   collection.removeAtIndex(1)
}
```

_I traced this to an issue with the wrong initialiser being called for_ `ArrayBindingObserver`

`list.observe()` is defined in ObservableArray.swift Ln: 165, as:

```
public func observe() -> ArrayBindingObserver<ElementType> {
   return ArrayBindingObserver(array: self)
}
```

For the case above ElementType is `ObservableArray<Int>`, so the type of `self` is `ObservableArray<ObservableArray<Int>>`.
Swift doesn't seem to be able to correctly match the correct initialiser, so `observe()` ends up calling the convenience initialiser in ArrayBindingObserver.swift Ln: 27:

```
public convenience init(array: ObservableArray<T>) {       
   let sectionsArray = ObservableArray<ObservableArray<T>>([array])
   self.init(array: sectionsArray)
}
```

But `T` here is already `ObservableArray<Int>` and so it gets wrapped in an additional `Observable<T>` leading to a type of `ObservableArray<ObservableArray<ObservableArray<Int>>>`

It should be calling:

```
public init(array: ObservableArray<ObservableArray<T>>) {
   self.array = array        
   observeForArrayEvent()
   setupSectionObservers()
}
```

**Comment by yankodimitrov** [comment]
Thank you! Will look at it.

**Comment by yankodimitrov** [comment]
SignalKit 3.0 #16 replaces the <code>ObservableArray</code> with a new way for table and collection view bindings with <code>ObservableCollectionType</code>. :tada:
