### ISSUE TITLE
Undeclared CollectionChangeSet type in 3.0 release 

### ISSUE THREAD

**Issue by kafejo** [yankodimitrov/SignalKit#18]
When I try build 3.0 version from master, I get following errors

```
Use of undeclared CollectionChangeSet type
Use of undeclared ListOperationType
```

I really like this framework API and I would like to use it in our project. Could you fix this issue please? Thank you!

**Comment by yankodimitrov** [comment]
Just updated the podspec file as it was missing the folder with those files. Let me know if its working now.

Thanks

**Comment by kafejo** [comment]
It works! Thank you. Another thing is that it may be worth of mention that properties on NSObject subclasses must be marked as `dynamic` in order to be observable. Took me a while to figure out why the observation doesn't work. :-) Good job!
