### ISSUE TITLE
and() or() not() for SignalKit.Signal<(A, B, C)>

### ISSUE THREAD

**Issue by lexrus** [yankodimitrov/SignalKit#2]
This project is awesome. The syntax is much more vivid then ReactiveCocoa. But I just found some inconvenience.

Since we can combine several signals(Boolean wrapped in NSNumber) together with ReactiveCocoa:

``` swift
RAC(getCodeButton, "enabled") <-- RACSignal.combineLatest([validMobileSignal, isCountingSignal]).and()
```

While with SignalKit:

``` swift
combineLatest(mobileSignal, passwordSignal, smsCodeSignal)
    .map { $0.0 == $0.1 == $0.2 == true }
    .bindTo( isEnabled(fetchCodeButton) )
```

What if we add some convenient funcs like what ReactiveCocoa did.

``` swift
combineLatest(mobileSignal, passwordSignal, smsCodeSignal).and()
    .bindTo( isEnabled(fetchCodeButton) )
```

**Comment by yankodimitrov** [comment]
Hi,

I see how this can be improved, however <code>and()</code>, <code>or()</code> and <code>not()</code> are too ambiguous names for functions/methods.

Maybe something like this:

``` swift
combineLatest(mobileSignal, passwordSignal, smsCodeSignal)
    .map( reduceUsing(.And) )
    .bindTo( isEnabled(fetchCodeButton) )
```

Where <code>reduceUsing</code> is a curried function which accepts the kind of operation to use (<code>.And</code> or <code>.Or</code>) and returns a function which in its turn accepts a tuple with booleans that comes from applying <code>map</code> on the signal coming from <code>combineLatest</code>.

In Swift 2.0 using generic type extensions and protocol extensions we can implement something cleaner, so for now I will leave it as it is.

Thanks!

**Comment by yankodimitrov** [comment]
Im happy to tell you that in SignalKit 1.0.0 we now have <code>all</code> and <code>some</code> signal operations for signals of tuple type <code>(Bool, Bool)</code> and <code>(Bool, Bool, Bool)</code>

Now you can write your example like this:

``` swift
combineLatest(mobileSignal, passwordSignal, smsCodeSignal)
    .all { $0 == true }
    .bindTo(enabled: fetchCodeButton)
```

:tada:

**Comment by lexrus** [comment]
Nice.
But what if I have 4 or more params to pass?

**Comment by yankodimitrov** [comment]
You can combine them like this:

``` swift
let signalA = ...
let signalB = ...
let signalC = ...
let signalD = ...

let signalAB = combineLatest(signalA, signalB).all { $0 == true }
let signalCD = combineLatest(signalC, signalD).all { $0 == true }

combineLatest(signalAB, signalCD)
    .all { $0 == true }
    .bindTo(enabled: button)
```

Or you can implement a free function <code>combineLatest</code> similarly to the one included in SignalKit that accepts 4 signals and then add a extension to <code>SignalType</code> protocol for the methods <code>all</code> and <code>some</code> for a signal of tuple type <code>(Bool, Bool, Bool, Bool)</code>
