### ISSUE TITLE
The correct way to do an "initial" sendNext to get combineLatestWith to work

### ISSUE THREAD

**Issue by evgeniyd** [yankodimitrov/SignalKit#24]
I have two signals, one from color picker and second from `UISlider` (to pick color alpha):

     let pickedColor = Signal<UIColor>()
     let pickedAlpha = Signal<Float>()

I'd like to combine these two signals, so the obvious way is to use `combineLatestWith`:

    let _ = pickedColor.combineLatestWith(pickedAlpha).next { color, alpha  in
        print("color: \(color)\talpha: \(alpha)")
    }.disposeWith(disposableBag)

The values are not printed, until both controls do their first `sendNext`, which is expected.

I cannot wrap my head around the "nice" way to make that initial signals from both controls. Currently, what I do the next line after setting up `combineLatestWith` is:

    pickedColor.sendNext(colorPicker.color)
    pickedAlpha.sendNext(alphaSlider.value)

...but, I feel like I'm missing something obvious from FRP.

**Comment by yankodimitrov** [comment]
Instead of `Signal` try with `SignalValue` it sends its current value to any new observers and should call the `combineLatestWith(...)` handler.

I need to find some time to update and rework the library for Swift 3.
If you have any suggestions feel free to open an issue. 

:)

**Comment by evgeniyd** [comment]
Hi @yankodimitrov 

Thank you very much for answer. I'll try it a bit later.

Speaking about Swift 3. Have you seen [this private fork](https://github.com/tereks/SignalKit)? We use it in our Swift 3 app and it seems to work fine.

**Comment by yankodimitrov** [comment]
Hi @evgeniyd 

Yes I saw it, but along with the Swift 3 compatibility I want to refactor the framework.

Im working on it on the [SignalKit-5.0](https://github.com/yankodimitrov/SignalKit/tree/SignalKit-5.0) branch.

I will close the issue for now.
