### ISSUE TITLE
Pod doesn't include ObservableType

### ISSUE THREAD

**Issue by almostintuitive** [yankodimitrov/SignalKit#8]
Nice initiative, this is exactly what I'm looking for now, thank you!

Something I noticed: 
For some unknown reason, if I install the project from cocoapods, the file ObservableType is missing.
Does anyone have any ideas why?:)

![image](https://cloud.githubusercontent.com/assets/5416288/9450034/3909bed4-4a9e-11e5-8da6-313452f464f9.png)

**Comment by almostintuitive** [comment]
ohh that's failed debugging on my part, the pod is out of date,  can we have an update please?:)

for anyone who wants to use it in the meantime:
pod 'SignalKit', :git => 'https://github.com/yankodimitrov/SignalKit.git', :branch => 'master'

thank you!

**Comment by yankodimitrov** [comment]
Just updated the `podspec` 

Thanks!
